exports.config = {
    user: process.env.BROWSERSTACK_USERNAME,
    key: process.env.BROWSERSTACK_ACCESS_KEY,
    updateJob: false,
    specs: ["./test/specs/**.e2e.js"],
    exclude: [],
    capabilities: [
        {
            project: "First Webdriverio Android Project",
            build: "Webdriverio Android",
            name: "first_test",
            device: "Google Pixel 3",
            os_version: "9.0",
            app:process.env.BROWSERSTACK_APP_ID || "bs://b5627fd64c15f366e16b5648bef694d6f1241acd",
            "browserstack.debug": true,
        },
    ],
    services: ["appium", "browserstack"],
    logLevel: "info",
    coloredLogs: true,
    screenshotPath: "./errorShots/",
    baseUrl: "",
    waitforTimeout: 10000,
    connectionRetryTimeout: 90000,
    connectionRetryCount: 3,
    framework: "mocha",
    mochaOpts: {
        ui: "bdd",
        timeout: 20000,
    },
};
